### ISSUE TITLE
Can not import NoneType from types

### ISSUE THREAD

**Issue by everythoughthelps** [dendenxu/mipnerf360-pytorch-minus#4]
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from lib.config import cfg, args
  File "/media/data4/panmeng/mipnerf360minus/lib/config/__init__.py", line 1, in <module>
    from .config import cfg, args
  File "/media/data4/panmeng/mipnerf360minus/lib/config/config.py", line 11, in <module>
    from lib.utils.log_utils import log
  File "/media/data4/panmeng/mipnerf360minus/lib/utils/log_utils.py", line 5, in <module>
    from types import NoneType
ImportError: cannot import name 'NoneType' from 'types' (

**Comment by dendenxu** [comment]
Hi! Thanks for bringing attension to the issue. Which version of Python are you using? I tested on 3.10 and 3.11 and the import works on these versions.

**Comment by everythoughthelps** [comment]
> Hi! Thanks for bringing attension to the issue. Which version of Python are you using? I tested on 3.10 and 3.11 and the import works on these versions.

I'll try, thanks!
